test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare, :r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare, :r2, :secret_access_key) %>
  endpoint: https://<%= Rails.application.credentials.dig(:cloudflare, :account_id) %>.r2.cloudflarestorage.com
  region: auto
  bucket: <%= Rails.application.credentials.dig(:cloudflare, :r2, :bucket_name) %>
  force_path_style: true
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
